FROM python:3.8
        EXPOSE 8501
        WORKDIR /query_model.py
        COPY requirements.txt ./requirements.txt
        RUN pip3 install -r requirements.txt
        COPY . .
        CMD streamlit run query_model.py --server.port $PORT --server.baseUrlPath ordlikhet 
        